server:
  port: 8081

spring:
  application:
    name: identity-service
  profiles:
    active: local        # ← default for local dev; Docker will override this

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}